name: Build buildx binary

on: [push, pull_request]

jobs:
  build-buildx:
    name: Build buildx binary
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: buildx docker image
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKER_BUILDKIT: 1
        PREFER_BUILDCTL: 1
      run: |
        docker build --tag buildx --target release --platform=local .

    - name: buildx building
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKER_BUILDKIT: 1
        PREFER_BUILDCTL: 1
      run: |
        docker build --target release --platform=local --output ARTIFACTS .
        ARTIFACTS/buildx* version

    - name: publish
      uses: actions/upload-artifact@master
      with:
        name: buildx-${{ github.sha }}
        path: ./ARTIFACTS/

    - name: upload Docker image
      run: |
        docker login docker.pkg.github.com --username fernandomiguel --password ${{ secrets.PACKAGES_TOKEN }}
        docker tag buildx docker.pkg.github.com/fernandomiguel/buildx/buildx:${{ github.sha }}-${INVOCATION_ID}
        docker push docker.pkg.github.com/fernandomiguel/buildx/buildx:${{ github.sha }}-${INVOCATION_ID}